#ifndef __INC_METIN_II_COMMON_BILLING_H__
#define __INC_METIN_II_COMMON_BILLING_H__

enum EBillingTypes
{
	BILLING_NONE,
	BILLING_IP_FREE,
	BILLING_FREE,
	BILLING_IP_TIME,
	BILLING_IP_DAY,
	BILLING_TIME,
	BILLING_DAY,
};

#endif
